//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.DataBaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.TestTries = new HashSet<TestTry>();
        }
    
        public int ID { get; set; }
        public int QuestionNumber { get; set; }
        public string Picture { get; set; }
        public string Sound { get; set; }
        public int Choice1 { get; set; }
        public int Choice2 { get; set; }
        public Nullable<int> Choice3 { get; set; }
        public Nullable<int> Choice4 { get; set; }
        public string CorrectAnswer { get; set; }
        public int SeriesID { get; set; }
    
        public virtual Serie Serie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestTry> TestTries { get; set; }
    }
}
